Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2018-09, with the labels that each got.

#1123 (maint) - Change versioning comparison
  spec/spec_helper_acceptance.rb
Labels: bugfix

#1125 (MODULES-7827) - Update i18n test logic for puppet 6
  spec/acceptance/locales_spec.rb
  spec/spec_helper_acceptance.rb
Labels: maintenance

#1127 pdksync - (MODULES-6805) metadata.json shows support for puppet 6
  metadata.json
Labels: feature

#1131 (MODULES-7903) - 6.2.0 Release Prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1132 Release mergeback 6.2.0
  CHANGELOG.md
  metadata.json
Labels: maintenance
