Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2018-12, with the labels that each got.

#1145 (MODULES-8193) - Removal of inbuilt deepmerge and dirname functions
  lib/puppet/functions/mysql/deepmerge.rb
  lib/puppet/functions/mysql/dirname.rb
  lib/puppet/parser/functions/mysql_deepmerge.rb
  lib/puppet/parser/functions/mysql_dirname.rb
  manifests/backup/mysqlbackup.pp
  manifests/server.pp
  manifests/server/binarylog.pp
  manifests/server/config.pp
  spec/functions/mysql_deepmerge_spec.rb
  spec/functions/mysql_dirname_spec.rb
  spec/unit/puppet/functions/mysql_deepmerge_spec.rb
Labels: backwards-incompatible

#1146 (MODULES-8144) - Add support for SLES 15
  metadata.json
Labels: feature

#1148 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#1150 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix
