Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2018-05, with the labels that each got.

#1062 (PDOC-210) add Puppet Strings documentation
  README.md
  REFERENCE.md
  lib/puppet/parser/functions/mysql_deepmerge.rb
  lib/puppet/parser/functions/mysql_dirname.rb
  lib/puppet/parser/functions/mysql_password.rb
  lib/puppet/type/mysql_database.rb
  lib/puppet/type/mysql_datadir.rb
  lib/puppet/type/mysql_grant.rb
  lib/puppet/type/mysql_plugin.rb
  lib/puppet/type/mysql_user.rb
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/bindings.pp
  manifests/bindings/client_dev.pp
  manifests/bindings/daemon_dev.pp
  manifests/bindings/java.pp
  manifests/bindings/perl.pp
  manifests/bindings/php.pp
  manifests/bindings/python.pp
  manifests/bindings/ruby.pp
  manifests/client.pp
  manifests/client/install.pp
  manifests/db.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/account_security.pp
  manifests/server/backup.pp
  manifests/server/binarylog.pp
  manifests/server/config.pp
  manifests/server/install.pp
  manifests/server/installdb.pp
  manifests/server/monitor.pp
  manifests/server/mysqltuner.pp
  manifests/server/providers.pp
  manifests/server/root_password.pp
  manifests/server/service.pp
Labels: feature

#1078 (MODULES-7160) fix manifest comment and re-generate REFERENCE.md
  REFERENCE.md
  manifests/server/providers.pp
Labels: maintenance

#942 Replaced 'DROP USER' with 'DROP USER IF EXISTS'
  lib/puppet/provider/mysql_user/mysql.rb
  spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Labels: feature, needs-rebase

#1083 Support for optional__args and prescript to mysqldump backup provider
  manifests/server/backup.pp
  templates/mysqlbackup.sh.erb
Labels: feature
