Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2019-11, with the labels that each got.

#1251 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#1253 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#1254 (FM-8677) - Support added for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#1256 (MODULES-10114) Confine fact for only when mysql is in PATH
  lib/facter/mysql_version.rb
Labels: bugfix

#1257 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  metadata.json
  spec/spec_helper.rb
Labels: maintenance
