Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2019-05, with the labels that each got.

#1193 (MODULES-9017) - update metadata to support current version of stdlib
  metadata.json
Labels: maintenance

#1197 MODULES-9160 - release 9.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1195 (MODULES-6875,MODULES-7487) - Fix mariadb mysql_user password idempotency
  lib/puppet/provider/mysql.rb
  lib/puppet/provider/mysql_user/mysql.rb
Labels: bugfix

#1199 (FM-8029) Add RedHat 8 support
  metadata.json
  spec/acceptance/locales_spec.rb
  spec/spec_helper_acceptance.rb
Labels: feature
