Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2019-09, with the labels that each got.

#1229 Fix .travis file
  .travis.yml
Labels: maintenance

#1207 Make backup success file path configurable
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/server/backup.pp
  spec/classes/mysql_server_backup_spec.rb
  templates/mysqlbackup.sh.erb
  templates/xtrabackup.sh.erb
Labels: feature

#1230 FM-8406 add support on Debian10
  metadata.json
  provision.yaml
Labels: feature

#1227 No package under FreeBSD
  manifests/backup/mysqldump.pp
Labels: bugfix

#1226 Fix group on FreeBSD
  manifests/server/backup.pp
Labels: bugfix

#1232 (maint) Add a codeowners file
  CODEOWNERS
Labels: maintenance

#1236 add package lsb_release for puppet fact, and fix grant test
  spec/acceptance/types/mysql_grant_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#1238 pdksync - Remove nodesets
  spec/acceptance/nodesets/centos-7-x64.yml
  spec/acceptance/nodesets/debian-8-x64.yml
  spec/acceptance/nodesets/default.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
Labels: maintenance
