Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2019-12, with the labels that each got.

#1262 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#1261 Add centos 8 travis build
  .travis.yml
  provision.yaml
Labels: maintenance

#1263 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1259 Fix test suite when mysqld is not installed
  spec/unit/facter/mysqld_version_spec.rb
Labels: maintenance

#1265 Add Github Actions release workflow
  .github/workflows/release.yml
Labels: maintenance

#1264 Fix java and ruby binding packages for Debian 10
  manifests/params.pp
Labels: bugfix

#1266 Fix facter mysql version unit test
  spec/unit/facter/mysql_version_spec.rb
Labels: maintenance

#1271 Merge back for Release version 10.3.0
  CHANGELOG.md
  metadata.json
Labels: maintenance
