Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2019-04, with the labels that each got.

#1176 Rotate option for xtrabackup script
  templates/xtrabackup.sh.erb
Labels: feature, needs-docs

#1163 Set correct packagename for ruby_mysql on Ubuntu 18.04
  manifests/params.pp
Labels: bugfix

#1177 (MODULES-8826) - 8.1.0 Release Prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1179 (MODULES-8830) Release mergeback 8.1.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1184 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#1181 (MODULES-8886) Revert removal of deepmerge function
  lib/puppet/functions/mysql/normalise_and_deepmerge.rb
  manifests/backup/mysqlbackup.pp
  manifests/server.pp
  spec/functions/mysql_normalise_and_deepmerge_spec.rb
Labels: bugfix

#1186 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance
