Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2019-03, with the labels that each got.

#1162 FM 7783 - Test Audit making testing more efficient
  lib/puppet/functions/mysql_password.rb
  lib/puppet/functions/mysql_strip_hash.rb
  lib/puppet/parser/functions/mysql_strip_hash.rb
  spec/acceptance/locales_spec.rb
  spec/acceptance/mysql_backup_spec.rb
  spec/acceptance/mysql_db_spec.rb
  spec/acceptance/mysql_server_spec.rb
  spec/acceptance/sql_task_spec.rb
  spec/acceptance/types/mysql_database_spec.rb
  spec/acceptance/types/mysql_plugin_spec.rb
  spec/classes/mysql_client_spec.rb
  spec/defines/mysql_db_spec.rb
  spec/functions/mysql_password_spec.rb
  spec/functions/mysql_password_wrapper_spec.rb
  spec/functions/mysql_strip_hash_wrapper_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_local.rb
  spec/unit/facter/mysql_server_id_spec.rb
  spec/unit/puppet/type/mysql_user_spec.rb
Labels: maintenance

#1164 pdksync - Remove .project from .gitignore
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1169 (maint) Merging returned translations into master
  readmes/README_ja_JP.md
  readmes/REFERENCE_ja_JP.md
Labels: maintenance

#1170 (MODULES-8684) - Removing private tags from Puppet Types
  REFERENCE.md
  lib/puppet/type/mysql_grant.rb
  lib/puppet/type/mysql_user.rb
Labels: bugfix

#1172 (MODULES-8753) - 8.0.1 Release Prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1171 Add support for dynamic backupmethods/mariabackup
  README.md
  REFERENCE.md
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/server/backup.pp
  spec/classes/mysql_server_backup_spec.rb
  templates/mysqlbackup.sh.erb
  templates/xtrabackup.sh.erb
Labels: feature

#1173 (MODULES-8757) - Release mergeback 8.0.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1165 Update Percona example
  README.md
Labels: maintenance

#1174 (MODULES-6627) Remove unused --host flags from mysqlcaller
  lib/puppet/provider/mysql.rb
Labels: bugfix
