Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2020-11, with the labels that each got.

#1337 (MAINT) Install curl package on Debian/Ubuntu
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#1323 Fix package for python bindings on Ubuntu 20.04
  manifests/params.pp
Labels: bugfix

#1328 Add compatibility for Amazon Linux 2
  manifests/params.pp
Labels: feature

#1341 Release version 10.8.0 Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1340 (IAC-996) Removal of inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  CONTRIBUTING.md
  README.md
  lib/puppet/provider/mysql_login_path/inifile.rb
  metadata.json
  readmes/README_ja_JP.md
Labels: feature

#1342 pdksync - Update pdk-templates for gitpod and codespaces support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.Dockerfile
  .gitpod.yml
  .pdkignore
  .rubocop.yml
  .sync.yml
  Gemfile
  data/common.yaml
  hiera.yaml
  metadata.json
Labels: maintenance

#1344 pdksync - (maint) Add release_checks_7 config to provision.yaml
  provision.yaml
Labels: maintenance
