Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2020-06, with the labels that each got.

#1307 Use ALTER USER for mariadb 10.2.0 or newer
  lib/puppet/provider/mysql_user/mysql.rb
Labels: maintenance

#1303 (IAC-746) - Add ubuntu 20.04 support
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  .sync.yml
  .travis.yml
  manifests/params.pp
  metadata.json
  provision.yaml
  spec/acceptance/types/mysql_grant_spec.rb
Labels: feature

#1233 change split on whitespace to split on tab in mysql_user
  lib/puppet/provider/mysql_user/mysql.rb
  spec/acceptance/types/mysql_user_spec.rb
  spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Labels: bugfix

#1308 pdksync - (IAC-886) Back out SLES 11 from release checks
  provision.yaml
Labels: maintenance

#1305 Add managed_dirs parameter
  REFERENCE.md
  manifests/server.pp
  manifests/server/config.pp
  spec/acceptance/mysql_mariadb_spec.rb
Labels: bugfix

#1311 Release mergeback version 10.6.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
