Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2020-03, with the labels that each got.

#1287 (MODULES-10562) - v10.4.0 Release Preperation
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1288 (MODULES-10564) Release Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1284 Allow changing the mysql-config-file group-ownership
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  spec/classes/mycnf_template_spec.rb
Labels: feature

#1290 (MAINT) Update docker image names
  provision.yaml
Labels: maintenance

#1289 pdksync - (IAC-555) - Remove distelli-manifest.yml
  distelli-manifest.yml
Labels: maintenance

#1281 pdksync - Add weekly scheduled workflows
  .github/workflows/weekly.yml
Labels: maintenance

#1194 Fix binarylog by allowing users to specify managed directories
  manifests/params.pp
  manifests/server.pp
  manifests/server/binarylog.pp
  manifests/server/config.pp
  manifests/server/managed_dirs.pp
Labels: bugfix

#1293 Improve differences between generated mysql service id values
  lib/facter/mysql_server_id.rb
  spec/unit/facter/mysql_server_id_spec.rb
Labels: bugfix
