Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2021-02, with the labels that each got.

#1364 (IAC-1428) Release Prep PR version 10.10.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1365 Merge back PR for Release v10.10.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1363 Support compression command and extension
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/server/backup.pp
  spec/classes/mysql_backup_mysqldump_spec.rb
  templates/mysqlbackup.sh.erb
Labels: feature

#1366 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  Rakefile
  metadata.json
Labels: backwards-incompatible

#1367 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#1369 pdksync - (MAINT) Remove RHEL 5 family support
  metadata.json
Labels: maintenance

#1370 pdksync - (MAINT) Remove SLES 11 support
  metadata.json
Labels: maintenance
