Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2021-07, with the labels that each got.

#1412 (maint) Comment out pending test
  spec/functions/mysql_password_spec.rb
Labels: maintenance

#1405 (MODULES-11115) add Rocky Linux 8 compatibility
  manifests/params.pp
Labels: feature

#1416 (maint) Update the since_tag
  CHANGELOG.md
  HISTORY.md
Labels: maintenance

#1406 Remove EOL platforms Debian 8 and Ubuntu 14.04
  .nodeset.yml
  README.md
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/params.pp
  metadata.json
  provision.yaml
  spec/acceptance/mysql_backup_spec.rb
  spec/acceptance/mysql_mariadb_spec.rb
  spec/acceptance/types/mysql_login_path_spec.rb
Labels: backwards-incompatible

#1408 Deprecate mysql::server::monitor and show as an example
  README.md
  examples/monitor.pp
  manifests/server/monitor.pp
  spec/classes/mysql_server_monitor_spec.rb
Labels: backwards-incompatible

#1409 Deprecate mysql::server::mysqltuner and show it as an example
  README.md
  examples/mysqltuner.pp
  manifests/server/mysqltuner.pp
  spec/classes/mysql_server_mysqltuner_spec.rb
Labels: backwards-incompatible

#1421 Update changelog_since_tag
  .github/workflows/pr_test.yml
  .github/workflows/spec.yml
  .puppet-lint.rc
  .sync.yml
  Rakefile
  metadata.json
Labels: maintenance

#1422 Update since_tag and history.md
  .sync.yml
  Rakefile
Labels: maintenance

#1423 pdksync - (maint) - Updating Contribution Guidelines
  CONTRIBUTING.md
Labels: maintenance

#1424 Release mergeback version 12.0.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
