Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2022-08, with the labels that each got.

#1481 [Compatibility] Add Raspbian OS to provider configuration
  manifests/params.pp
Labels: feature, community

#1480 Allow excludedatabases when using file_per_database
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/server/backup.pp
  spec/classes/mysql_backup_mysqldump_spec.rb
  templates/mysqlbackup.sh.erb
Labels: community

#1483 pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  manifests/backup/xtrabackup.pp
  metadata.json
  spec/acceptance/00_mysql_server_spec.rb
  spec/acceptance/01_mysql_db_spec.rb
  spec/acceptance/04_mysql_backup_spec.rb
  spec/acceptance/types/mysql_database_spec.rb
  spec/acceptance/types/mysql_grant_spec.rb
  spec/classes/mysql_backup_xtrabackup_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#1486 Harden service class
  manifests/server/service.pp
Labels: bugfix

#1487 Harden config class
  manifests/server/config.pp
Labels: bugfix

#1484 Harden db defined type
  manifests/db.pp
  spec/acceptance/01_mysql_db_spec.rb
  spec/acceptance/types/mysql_grant_spec.rb
  spec/defines/mysql_db_spec.rb
Labels: bugfix, backwards-incompatible

#1485 Harden root password class
  manifests/params.pp
  manifests/server.pp
  manifests/server/root_password.pp
  pdk.yaml
  spec/acceptance/01_mysql_db_spec.rb
  spec/classes/mysql_server_spec.rb
Labels: bugfix

#1488 (MAINT) Fix acceptance tests
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  spec/acceptance/00_mysql_server_spec.rb
  spec/acceptance/04_mysql_backup_spec.rb
  spec/acceptance/05_mysql_xtrabackup_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#1490 fixing typo for release
  manifests/db.pp
Labels: maintenance
