Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2022-04, with the labels that each got.

#1464 pdksync - PDKSYNC Update labeller trigger
  .github/workflows/labeller.yml
Labels: maintenance

#1460 release prep v12.0.2
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1425 Solve issue with repeated restarts if ssl-disable is true
  manifests/server.pp
  manifests/server/config.pp
Labels: bugfix, community

#1467 pdksync - (Maint) PDK Update
  .github/workflows/nightly.yml
  .github/workflows/spec.yml
  .puppet-lint.rc
  .sync.yml
  Rakefile
  lib/facter/mysql_server_id.rb
  lib/puppet/provider/mysql_grant/mysql.rb
  manifests/backup/mysqlbackup.pp
  manifests/bindings.pp
  manifests/params.pp
  metadata.json
Labels: maintenance

#1418 Deprecate unsupported Solaris platform
  hiera.yaml
  manifests/params.pp
  templates/mysqlbackup.sh.erb
  templates/xtrabackup.sh.erb
Labels: maintenance, community
