Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2022-12, with the labels that each got.

#1513 do not emit other ssl directives when ssl = false
  spec/classes/mycnf_template_spec.rb
  templates/my.cnf.erb
Labels: community

#1517 (GH-1516) Update sql example to use array
  README.md
Labels: bugfix

#1519 (GH-1518) Declare minimum Puppet version 6.24.0
  metadata.json
Labels: bugfix

#1524 fix naming in documentation
  REFERENCE.md
  lib/puppet/functions/mysql/password.rb
Labels: maintenance, community
