Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2023-04, with the labels that each got.

#1549 fixtures.yml: Delete legacy symlink
  .fixtures.yml
Labels: community

#1552 move static data from params to server class
  REFERENCE.md
  manifests/params.pp
  manifests/server.pp
Labels: bugfix, community

#1555 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#1556 (Release) v13.3.0 Release Prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1558 (maint) Release Prep v14.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1561 pdksync - (MAINT) - Add env variables to ci
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: maintenance
