Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2023-05, with the labels that each got.

#1564 Fix broken sensitive parameter for mysql::password
  lib/puppet/functions/mysql/password.rb
  lib/puppet/functions/mysql_password.rb
  spec/functions/mysql_password_spec.rb
Labels: bugfix, community

#1567 pdksync - (CONT-930) - Roll out new changelog generator
  .github/workflows/auto_release.yml
  .github/workflows/release_prep.yml
Labels: maintenance

#1568 (CONT-903) Use checkout@v3
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: maintenance

#1570 pdksync - (CONT-1001) Add litmus ~> 1.0
  Gemfile
Labels: maintenance

#1569 (CONT-576) allow deferred function for token & secrets
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/db.pp
  manifests/server/root_password.pp
  metadata.json
  spec/unit/puppet/provider/mysql_login_path/mysql_login_path_spec.rb
  templates/meb.cnf.epp
  templates/meb.cnf.erb
Labels: feature
