Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2023-06, with the labels that each got.

#1572 pdksync - (MAINT) - Allow Stdlib 9.x
  manifests/backup/mysqlbackup.pp
  manifests/backup/mysqldump.pp
  manifests/backup/xtrabackup.pp
  manifests/server/config.pp
  manifests/server/service.pp
  metadata.json
  spec/acceptance/05_mysql_xtrabackup_spec.rb
Labels: feature

#1577 pdksync - (CONT-990) - Adding Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance

#1537 Improve documentation
  REFERENCE.md
  lib/puppet/type/mysql_database.rb
  lib/puppet/type/mysql_datadir.rb
  lib/puppet/type/mysql_grant.rb
  lib/puppet/type/mysql_login_path.rb
  lib/puppet/type/mysql_plugin.rb
  lib/puppet/type/mysql_user.rb
  manifests/db.pp
Labels: maintenance, community

#1534 remove ssl-disable notify
  manifests/server.pp
Labels: bugfix, community
