Repository puppetlabs/puppetlabs-mysql, pull requests merged in 2024-07, with the labels that each got.

#1634 (CAT-1919) - Handle scenario when user input password in <anything-in-caps-with-alpha-numeric>*<alpha-numeric-40-chars-in-caps>
  lib/puppet/functions/mysql/password.rb
  spec/acceptance/00_mysql_server_spec.rb
  spec/functions/mysql_password_spec.rb
Labels: bugfix

#1635 (MAINT) Fixing documentation syntax of innobackup function
  lib/puppet/functions/mysql/innobackupex_args.rb
Labels: bugfix, maintenance

#1625 Remove deprecated option expire_logs_days from default config
  manifests/params.pp
Labels: backwards-incompatible, community

#1624 (#1619) mysq::db: update charset/collate to utf8mb3/utf8mb3_general_ci
  manifests/db.pp
Labels: backwards-incompatible, community

#1641 pdksync - (CAT-1963) - Remove Labeller
  .github/workflows/labeller.yml
Labels: maintenance
